
const _ = {
    LOCK_POTRAIT: "LOCK_POTRAIT",
    LOCK_POTRAIT_UP: "LOCK_POTRAIT_UP",
    LOCK_POTRAIT_DOWN: "LOCK_POTRAIT_DOWN",
    LOCK_LANDSCAPE: "LOCK_LANDSCAPE",
    LOCK_LANDSCAPE_RIGHT: "LOCK_LANDSCAPE_RIGHT",
    LOCK_LANDSCAPE_LEFT: "LOCK_LANDSCAPE_LEFT",
    LOCK_DEFAULT: "LOCK_DEFAULT",
    LOCK_OTHER: "LOCK_OTHER",
    LOCK_UNKNOWN: "LOCK_UNKNOWN",
    LOCK_ALL: "LOCK_ALL",
}
export default _